services:
  ai-agent:
    build: .
    container_name: ai-agent
    ports:
      - "8083:8000"
    env_file:
      - .env
    restart: always
    volumes:
      - /opt/docker/ai-agent:/app
    environment:
      - REDIS_URL=redis://redis:6379/0  # Damit dein Agent wei√ü, wo Redis ist
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: ai-agent-redis
    restart: always